# Site settings
title: K6312 INFORMATION MINING & ANALYSIS Spring 2020
email: zhenghua.chen@ntu.edu.sg
description: "Course webiste for K6312"
#baseurl: ""
#url: ""
#github_username: ""
  
theme: jekyll-theme-minimal
