# Site settings
title: H6751 Text and Web Mining  Spring 2020
email: diszr@nus.edu.sg
description: "Course webiste for H6751"
#baseurl: ""
#url: ""
#github_username: ""
  
theme: jekyll-theme-minimal
