# Site settings
title: BT5153 Advanced Topics in  Machine Learning for Business Analytics  Spring 19-20
email: diszr@nus.edu.sg
description: "Course webiste for BT5153"
baseurl: ""
url: "http://nusmsba.github.io"
github_username: ""
  
theme: jekyll-theme-minimal
